version: "3"

services:
  api:
    tty: true
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm run start:dev"
    container_name: "${PROJECTID}_api"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "${HOST_PORT}:3000"
    networks:
      - common_network
  db:
    container_name: ${PROJECTID}_mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${LOCAL_MYSQL_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PROJECTID}
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Kolkata
    networks:
      - common_network
  admin:
    container_name: ${PROJECTID}_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "${LOCAL_PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=${PROJECTID}_mysql
      - PMA_USER=root
      - PMA_PASSWORD=${PROJECTID}
      - UPLOAD_LIMIT=3000000000
      - TZ=Asia/Kolkata
    networks:
      - common_network
networks:
  common_network:
    name: common_network
