FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache tzdata
ENV TZ Asia/Kolkata
ENV PATH /app/node_modules/.bin:$PATH
RUN npm i -g @nestjs/cli -y
RUN apk add ffmpeg

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

#lint check
RUN npm run lint

CMD ["npm", "run", "start:prod"]
