version: "3"

services:
  api:
    tty: true
    working_dir: /app
    command: >
      sh -c "npm install && npm run migration:run && npm run build && npm run start:prod"
    container_name: "${PROJECTID}_api"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.stag
    volumes:
      - ".:/app"
    ports:
      - "${HOST_PORT}:3000"
    networks:
      - common_network
networks:
  common_network:
    name: common_network
